export const API_KEY = "925bcf2c47ee4923a5a203853241101"
export const BASE_URL = "http://api.weatherapi.com/v1/"
export const SUN_BASE_URL = "https://api.sunrisesunset.io/json"
export const CURRENT = "current.json?key="
export const FORECAST = "forecast.json?key="